# The same as the train.yaml but you could customize the parameters for testing.
data:
  class_path: data_loader.SPencn_NSdns_RIRreal.CleanMelDataModule
  init_args:
    speech_dir: YOUR_SPEECH_DIR/
    noise_dir: YOUR_NOISE_DIR/
    rir_dir: YOUR_RIR_DIR/
    datasets: ['SimTrain', 'SimVal', 'SimTest', ['SimVal']]
    audio_time_len: [4.0, 4.0, null]
    snr: [-5, 20]
    batch_size: [2, 1]
    dataset_len: [100000, 3000, 3000]

model_checkpoint: # remove this if it cause any errors
  save_top_k: -1 # save every checkpoint for testing the performance on utterance/session0 and pick the best checkpoint for evaulating other sessions