seed_everything: 2
trainer:
  gradient_clip_val: 10
  gradient_clip_algorithm: norm
  devices: null
  accelerator: gpu
  strategy: ddp_find_unused_parameters_false
  sync_batchnorm: false
  precision: 32
  num_sanity_val_steps: 3
  deterministic: true

model:
  arch:
    class_path: models.arch.CleanMel_mamba.CleanMel
    init_args:
      dim_input: 2
      dim_output: 1
      num_layers: 8
      dim_hidden: 96
      layer_linear_freq: 1
      kernel_size: [5, 3]
      conv_groups: []
      num_freqs=257,
      mamba_state=16,
      mamba_conv_kernel=4,
      online=online,
      _mel_options={"sr": 16000, "n_fft": 512, "n_mels": 80},
  stft:
    class_path: models.io.stft.InputSTFT
    init_args:
      n_fft: 512 
      n_win: 512 
      n_hop: 128
      center: true 
      normalize: false 
      onesided: true 
      online: false
  target_stft:
    class_path: models.io.stft.TargetMel
    init_args:
        sample_rate: 16000
        n_fft: 512
        n_win: 512
        n_hop: 128
        n_mels: 80
        f_min: 0
        f_max: 8000
        power: 2
        center: true
        normalize: false
        onesided: true
        mel_norm: "slaney"
        mel_scale: "slaney"
        librosa_mel: true
        online: false
  optimizer: [AdamW, { lr: 0.001, weight_decay: 0.001}]
  lr_scheduler: [ExponentialLR, { gamma: 0.99 }]
  exp_name: exp
  metrics: [DNSMOS]
  log_eps: 1e-7