
name2abbr = {
    "Cafeteria1": "CAF1",
    "OfficeLobby": "OFFL",
    "BasketballCourt1": "BAS1",
    "BadmintonCourt1": "BAD1",
    "Classroom1": "CLA1",
    "OfficeRoom3": "OFR3",
    "LivingRoom1": "LIV1",
    "LivingRoom2": "LIV2",
    "Gym": "GYM",
    "Market": "MARK",
    "Car-Gasoline": "CARG",
    "Car-Electric": "CARE",
    "LivingRoom3": "LIV3",
    "LivingRoom4": "LIV4",
    "LivingRoom5": "LIV5",
    "LivingRoom6": "LIV6",
    "LivingRoom7": "LIV7",
    "LivingRoom8": "LIV8",
    "Library": "LIBR",
    "Classroom2": "CLA2",
    "SunkenPlaza1": "SUN1",
    "Auditorium": "AUDI",
    "OfficeRoom4": "OFR4",
    "UndergroundParking1": "UND1",
    "Classroom3": "CLA3",
    "Bus-Electric": "BUSE",
    "Terrace": "TER1",
    "Laundry": "LAUN",
    "LivingRoom9": "LIV9",
    "Terrace2": "TER2",
    "Roadside1": "ROA1",
    "ConstructionPlant": "CONS",
    "Cafeteria2": "CAF2",
    "Park": "PARK",
    "PedestrianStreet": "PEDE",
    "BarberShop": "BARB",
    "ShoppingMall": "SHOP",
    "SunkenPlaza2": "SUN2",
    "Roadside2": "ROA2",
    "Subway-Electric": "SUBE",
    "OfficeRoom1": "OFR1",
    "OfficeRoom2": "OFR2",
    "UndergroundParking2": "UND2",
    "Cafeteria3": "CAF3",
    "BadmintonCourt2": "BAD2",
    "BasketballCourt2": "BAS2",
}

# {
#     "Canteen": "CT",
#     "No1GateHall": "N1G",
#     "SportsField": "SF",
#     "BadmintonCourt": "BC",
#     "Classroom1": "CR1",
#     "MeetingRoom": "MR",
#     "Apartment1LivingRoom": "A1LR",
#     "Apartment1BedRoom": "A1BR",
#     "Gym": "GYM",
#     "VegetableMarket": "VM",
#     "GasolineCar": "GC",
#     "ElectricVehicle": "EV",
#     "Hotel": "HTL",
#     "Loft": "LFT",
#     "Apartment2LivingRoom": "A2LR",
#     "Apartment2BedRoom": "A2BR",
#     "PartyHouse": "PH",
#     "Dorm": "DRM",
#     "Library": "LBR",
#     "LectureHall": "LH",
#     "SunkenPlaza1": "SP1",
#     "Auditorium": "ADT",
#     "Karaoke": "KTV",
#     "UndergroundParking": "UP",
#     "Classroom2": "CR2",
#     "Bus": "BS",
#     "Terrace": "TRC",
#     "Laundry": "LDR",
#     "Apartment3Decoration": "A3D",
#     "BeneathCourtyardEave": "BCE",
#     "CrossRoad": "CRR",
#     "ConstructionPlant": "CP",
#     "Restaurant": "RSTR",
#     "Park": "PRK",
#     "PedestrianStreet1": "PS1",
#     "PedestrianStreet2": "PS2",
#     "BarberShop": "BBS",
#     "Mall": "MLL",
#     "SunkenPlaza2": "SP2",
#     "Roadside": "RS",
#     "Metro": "MTR",
#     "OfficeRoom": "OR",
#     "CubicleOffice": "CBR",
#     "UndergroundParkingTest": "UPT",
#     "Canteen2": "CTT",
#     "BadmintonCourtTest": "BCT",
#     "BasketballCourt": "BSKC",
# }

set2abbr = {
    "test": "TEST",
    "val": "VAL",
    "train": "TRAIN"
}

# resolution2abbr = {
#     "high": "H",
#     "low": "L"
# }

state2abbr = {
    "static": "S",
    "moving": "M"
}